version: '3.3'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # - pgdata:/var/lib/postgresql/data
    
      - ./assets:/assets
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql-scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
volumes:
  pgdata:
    driver: local